on: 
  push

permissions:
  packages: write

jobs:
  microservices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        # Use v6.0.1
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Login to GitHub Container Registry
        # login-action @v3.6.0
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        # builx @v3.11.1
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
      - name: Build and push
        # build and push @v6.18.0
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
