name: Microservices CI/CD JDK 21
on:
  push

jobs:
  microservices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # use checkout v6.0.1
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Set up JDK 21
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Grant execute permission
        run: chmod +x gradlew
      
      - name: Build
        run: ./gradlew build
      
      - name: Upload JAR
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: microservice-jdk21-cicd
          path: build/libs/*.jar